/* Generated By:JavaCC: Do not edit this line. LanguageParserConstants.java */
package classes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LanguageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NovaLinha = 1;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int MAKE = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int CONST = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int REAL = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int GET = 17;
  /** RegularExpression Id. */
  int PUT = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 25;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 26;
  /** RegularExpression Id. */
  int PONTO = 27;
  /** RegularExpression Id. */
  int VIRGULA = 28;
  /** RegularExpression Id. */
  int DOISPONTOS = 29;
  /** RegularExpression Id. */
  int ATRIBUICAO = 30;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 31;
  /** RegularExpression Id. */
  int ADICAO = 32;
  /** RegularExpression Id. */
  int SUBTRACAO = 33;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 34;
  /** RegularExpression Id. */
  int DIVISAO = 35;
  /** RegularExpression Id. */
  int POTENCIA = 36;
  /** RegularExpression Id. */
  int DIVISAO_INTEIRA = 37;
  /** RegularExpression Id. */
  int RESTO = 38;
  /** RegularExpression Id. */
  int IGUAL = 39;
  /** RegularExpression Id. */
  int DIFERENTE = 40;
  /** RegularExpression Id. */
  int MENOR = 41;
  /** RegularExpression Id. */
  int MAIOR = 42;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 43;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 44;
  /** RegularExpression Id. */
  int E = 45;
  /** RegularExpression Id. */
  int OU = 46;
  /** RegularExpression Id. */
  int NAO = 47;
  /** RegularExpression Id. */
  int DIGITO = 48;
  /** RegularExpression Id. */
  int CONSTANTE_INTEIRA = 49;
  /** RegularExpression Id. */
  int CONSTANTE_REAL = 50;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 51;
  /** RegularExpression Id. */
  int LETRA = 52;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 54;
  /** RegularExpression Id. */
  int CONSTANTE_INTEIRA_INVALIDA = 55;
  /** RegularExpression Id. */
  int CONSTANTE_REAL_INVALIDA = 56;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL_INVALIDA = 57;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO_LINHA = 1;
  /** Lexical state. */
  int COMENTARIO_BLOCO = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NovaLinha>",
    "\"//\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"do\"",
    "\"make\"",
    "\"end\"",
    "\"const\"",
    "\"var\"",
    "\"int\"",
    "\"real\"",
    "\"char\"",
    "\"bool\"",
    "\"get\"",
    "\"put\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"->\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<DIGITO>",
    "<CONSTANTE_INTEIRA>",
    "<CONSTANTE_REAL>",
    "<CONSTANTE_LITERAL>",
    "<LETRA>",
    "<IDENTIFICADOR>",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_INTEIRA_INVALIDA>",
    "<CONSTANTE_REAL_INVALIDA>",
    "<CONSTANTE_LITERAL_INVALIDA>",
    "<IDENTIFICADOR_INVALIDO>",
  };

}
